## version: "3.1"

name: dss-laravel

services:
  mariadb:
    mem_limit: 2048m
    image: bitnami/mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - laravel-network
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    env_file: .env
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=null
    networks:
      - laravel-network

  laravel:
    depends_on:
      - mariadb
    image: bitnami/laravel
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=${MYSQL_USER}
      - DB_DATABASE=${MYSQL_DATABASE}
    volumes:
      - laravel_data:/app
    networks:
      - laravel-network


volumes:
  mariadb_data:
  laravel_data:

networks:
  laravel-network:
    driver: bridge